spring.application.name=voto
#ligação banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/meu_voto

# credenciais de acesso
spring.datasource.username=postgres
spring.datasource.password=Tecnologia#$1010

#criação de tabelas hibenate cria automatic
spring.jpa.hibernate.ddl-auto=update

# ver no terminal
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true