spring.application.name=voto
#ligação banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/votodb

# credenciais de acesso
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:}

#criação de tabelas hibenate cria automatic
spring.jpa.hibernate.ddl-auto=update

# ver no terminal
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true