spring.application.name=voto
#ligação banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/votodb

# credenciais de acesso
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:}

spring.config.import=optional:application-local.properties

#criação de tabelas hibenate cria automatic
spring.jpa.hibernate.ddl-auto=update

# ver no terminal
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Aumenta o limite de upload de arquivos para 50MB
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB